GET http://localhost:8080 HTTP/1.1
###
GET http://localhost:8080/api HTTP/1.1

###
POST http://localhost:8080/api/auth HTTP/1.1
Content-Type: application/json
Authorization: Bearer token

{
    "username": "admin@manilastudio.com",
    "password": "abc"
}

###
GET http://localhost:8080/api/private HTTP/1.1
Content-Type: application/json
Authorization: Bearer token

{
}

### Attempt with valid token
GET http://localhost:8080/api/private HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NTgyNDcwNzQsInN1YiI6ImUyN2IyYzg5LTFkMjQtNGNjYS1iMDhkLTAzN2M1ZTM5NjQxYiIsImRhdGEiOiIifQ.q50li12qPLI_tbwfvE964ZsN3Zs9tUwc_J3SqvN2LUrT0vWYfoFRyImC-xaJ1J7XSw_eDPr50LE4PZfIAyygkQ

{
}
